/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Asdrubal Rivas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public String contenidoArchivo;
    public boolean PrimeraVez;
    private String contenido;
    private String linea;
    private boolean archivoCargado = false;
    public MenuPrincipal() {
        initComponents();
        PrimeraVez = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VerGrafos = new javax.swing.JButton();
        ModificarGrafo = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        CargarTXT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerGrafos.setText("Ver Grafos");
        VerGrafos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerGrafosActionPerformed(evt);
            }
        });
        getContentPane().add(VerGrafos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 201, 78));

        ModificarGrafo.setText("ModificarGrafo");
        ModificarGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarGrafoActionPerformed(evt);
            }
        });
        getContentPane().add(ModificarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 201, 78));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 285, -1, -1));

        CargarTXT.setText("Cargar txt");
        CargarTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarTXTActionPerformed(evt);
            }
        });
        getContentPane().add(CargarTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 26, 201, 78));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void VerGrafosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerGrafosActionPerformed
        // TODO add your handling code here:
        InterfazGrafos GRAFOSVENTANA = new InterfazGrafos();
        GRAFOSVENTANA.setTitle("Grafos");
        GRAFOSVENTANA.setSize(800,700);
        GRAFOSVENTANA.setResizable(false);
        GRAFOSVENTANA.setLocationRelativeTo(null);
        GRAFOSVENTANA.setVisible(true);
        dispose();
        if(PrimeraVez == true){
        try (Scanner scanner = new Scanner(new File("C:\\Users\\Asdrubal Rivas\\Desktop\\Proyecto1-EDD\\PROYECTO.txt"))) {
                while (scanner.hasNextLine()) {
                    String linea = scanner.nextLine();
                    System.out.println(linea);
                    
                }
            } catch (FileNotFoundException ex) {
                System.err.println("Archivo no encontrado: " + ex.getMessage());
            }
        }else if(PrimeraVez == false){
            
            if (contenido != null && !contenido.isEmpty()) {
                System.err.println(contenido);
            }else{
                JOptionPane.showMessageDialog(rootPane, "No cargaste ningun txt");
            
            }
}
       
        
    }//GEN-LAST:event_VerGrafosActionPerformed

    private void CargarTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarTXTActionPerformed
        // TODO add your handling code here:
        if (archivoCargado || PrimeraVez == true){
            int existente = JOptionPane.showConfirmDialog(rootPane, "Ya registraste un txt..\nPara registrar otro necesitas guardar este primero\n¿Quieres guardar?");
            if (existente == JOptionPane.YES_OPTION){
                archivoCargado = false;
                
                File archivo = new File("archivo.txt");
                // Leer contenido del archivo
                //OJO Esto es temporal, aqui lo que guarda es el contenido del txt sin editar..
                //Osea, el txt original.. la idea es guardar el txt con los cambios del usuario
                //Todavia no se puede hacer eso porque aja... Ni idea de como hacer el grafo jaja
                String contenido = this.contenido;
                // Código para leer contenido del archivo y almacenarlo en la variable "contenido"

                // Guardar contenido en un archivo de texto en la computadora
                try {
                    FileOutputStream archivoSalida = new FileOutputStream("Archivo Guardado.txt");
                    PrintWriter escritor = new PrintWriter(archivoSalida);
                    escritor.print(contenido);
                    escritor.close();
                    JOptionPane.showMessageDialog(rootPane, "Archivo guardado exitosamente !!\nYa puedes cargar otro txt");
                    PrimeraVez = false;
                } catch (IOException e) {
                    System.out.println("Error al guardar archivo: " + e.getMessage());
                }
            
            }
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            try {
                File archivoSeleccionado = chooser.getSelectedFile();
                BufferedReader lector = new BufferedReader(new FileReader(archivoSeleccionado));
                String linea;
                contenido = "";
                while ((linea = lector.readLine()) != null) {
                    contenido += linea + "\n";
                    archivoCargado = true;
                }
                lector.close();
            } catch (IOException ex) {
                ex.printStackTrace();
        }
        }
        }
        
//        JFileChooser chooser = new JFileChooser();
//        int resultado = chooser.showOpenDialog(this);
//        if (resultado == JFileChooser.APPROVE_OPTION) {
//            try {
//                File archivoSeleccionado = chooser.getSelectedFile();
//                BufferedReader lector = new BufferedReader(new FileReader(archivoSeleccionado));
//                String linea;
//                contenido = "";
//                while ((linea = lector.readLine()) != null) {
//                    contenido += linea + "\n";
//                    archivoCargado = true;
//                }
//                lector.close();
//            } catch (IOException ex) {
//                ex.printStackTrace();
//            }
//        }
//
//    }
//    }
                                    
    }//GEN-LAST:event_CargarTXTActionPerformed

    private void ModificarGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarGrafoActionPerformed
        // TODO add your handling code here
        ModificarGrafo VENTANAUSUARIO = new ModificarGrafo();
        VENTANAUSUARIO.setTitle("Modificar Grafo");
        VENTANAUSUARIO.setSize(800,700);
        VENTANAUSUARIO.setResizable(false);
        VENTANAUSUARIO.setLocationRelativeTo(null);
        VENTANAUSUARIO.setVisible(true);
        dispose();
    }//GEN-LAST:event_ModificarGrafoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton CargarTXT;
    private javax.swing.JLabel Fondo;
    public javax.swing.JButton ModificarGrafo;
    private javax.swing.JButton VerGrafos;
    // End of variables declaration//GEN-END:variables
}
